---
abstract: 'Catalyst based application'
author:
  - THC,,,
build_requires:
  DBICx::TestDatabase: 0
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Treex-Web
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Assets: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::I18N: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0
  Catalyst::Runtime: 5.90007
  Catalyst::View::TT: 0
  CatalystX::SimpleLogin: 0
  Config::General: 0
  Crypt::Eksblowfish::Bcrypt: 0
  DBIx::Class::EncodedColumn: 0
  DBIx::Class::InflateColumn::Boolean: 0
  DBIx::Class::InflateColumn::FS: 0
  DBIx::Class::Migration: 0
  DBIx::Class::TimeStamp: 0
  DBIx::Class::UUIDColumns: 0
  Data::Uniqid: 0
  Email::Valid: 0
  HTML::FormHandler: 0.40001
  HTML::FormHandler::Model::DBIC: 0
  IPC::Run: 0
  Moose: 0
  SQL::Translator: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
