* What needs to be done
** [Treex::Web] #2 User accounts
   :PROPERTIES:
   :issue_id: 2
   :updated_on: 2013/02/09 16:29:17 +0100
   :assigned_to: Michal Sedlak
   :version:  alpha
   :END:
** [Treex::Web] #79 Scenarios list improvements
   :PROPERTIES:
   :issue_id: 79
   :updated_on: 2013/06/30 12:15:15 +0200
   :assigned_to: Michal Sedlak
   :version:  0.1
   :END:
** [Treex::Web] #113 Improved listings by Michal Sedlak
   :PROPERTIES:
   :issue_id: 113
   :updated_on: 2013/06/30 12:14:59 +0200
   :assigned_to: Michal Sedlak
   :version:  0.1
   :END:
** [Treex::Web] #112 Complete API documenation by Michal Sedlak
   :PROPERTIES:
   :issue_id: 112
   :updated_on: 2013/06/30 12:13:26 +0200
   :assigned_to: Michal Sedlak
   :version:  0.1
   :END:
** DONE Drawing trees
   Use [[http://d3js.org/][D3js.org]]

   Try not to trash everything I already have.
   Also consider dropping Coffescript
** DONE Post Resque patch
   SCHEDULED: <2013-06-01 Sat>

   patch: [[https://github.com/diegok/resque-perl/pull/8][Pull request]]

** DONE Fix utf8

   Seems like all utf8 input is broken. WTF??

** DONE Fix API to support angular resources
   SCHEDULED: <2013-04-15 Po>

   Url format should be *api/resource/:id/?:action*
   Where resource is in plural form. Nice fluent urls sucks for API.

   Rewrite everything to use $res->data instead of params and remove
   parametres encoding form Angular.

   Consider using [[http://apiary.io][Apiary]] for testing and documentation

** DONE Fix scenario CRUD
   SCHEDULED: <2013-04-16 Út>

   The scenario CRUD is still /not complete/ - at least on the fronted side.
