fs            = require 'fs'
path          = require 'path'
{spawn, exec} = require 'child_process'

srcDir = 'lib/coffee/'

treexFiles = [
  'util/ArrayList.coffee',
  'util/Color.coffee',
  'util/Point.coffee',

  'treex/TreeView.coffee',

  'treex/treeview/Canvas.coffee',
  'treex/treeview/Figure.coffee',
  'treex/treeview/NodeFigure.coffee',
  'treex/treeview/VectorFigure.coffee',
  'treex/treeview/SetFigure.coffee',
  'treex/treeview/Tree.coffee',
  'treex/treeview/Connection.coffee',
  'treex/treeview/ConnectionAnchor.coffee',

  'treex/treeview/shape/Line.coffee',
  'treex/treeview/shape/PolyLine.coffee',
  'treex/treeview/shape/Rectangle.coffee',

  'treex/treeview/layout/SimpleTreeLayout.coffee',
  'treex/treeview/layout/TreeNodeLocator.coffee'
]

task 'build:coffee', ->
  files = (srcDir+file for file in treexFiles)
  exec 'coffee -j static/js/treeview.js -c ' + files.join(' ')

task 'watch', ->
  files = srcDir+file for file in treexFiles
  exec 'coffee -j static/js/treeview.js -cw ' + files.join(' ')
