compile:
	coffee -j ./static/js/client.js -cw \
                  ./lib/client/util/*.coffee \
                  ./lib/client/treex/*.coffee \
                  ./lib/client/treex/treeview/*.coffee \
                  ./lib/client/treex/treeview/layout/*.coffee \
                  ./lib/client/treex/treeview/shape/*.coffee
